# -*- coding: utf-8 -*-
"""Functions and Data Structures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wHrtnSrSchloQGs3IwAHA-D3r2iRyl7p

# **Functions and Data Structures**

**User Defined Functions**
"""

# Defining and calling a custom function
def greet_engineer(name):
    return f"Welcome to the AI program, {name}!"

greeting = greet_engineer("Danish")
print(greeting)

"""**List Data Type**"""

# Creating and modifying a List (Mutable, ordered)
ai_libraries = ["NumPy", "Pandas", "Matplotlib"]
ai_libraries.append("Scikit-Learn")
print("Libraries:", ai_libraries)

"""**Tuple Data Type**"""

# Creating a Tuple (Immutable, ordered)
dimensions = (1920, 1080)
print(f"Width: {dimensions[0]}, Height: {dimensions[1]}")

"""**String Data Type**"""

# String manipulation and slicing
course = "Machine Learning"
print("First word:", course[0:7])

"""**Set Data Type**"""

# Sets do not allow duplicates
unique_numbers = {1, 2, 2, 3, 4, 4, 5}
print("Set removes duplicates:", unique_numbers)

"""**Dictionary Data Type**"""

# Storing key-value pairs
job_profile = {
    "title": "AI Engineer",
    "target_market": "Pakistan",
    "key_skills": ["Python", "Machine Learning", "NLP"]
}
print(f"Target Role: {job_profile['title']} in {job_profile['target_market']}")

"""**Exception Handling**"""

# Handling a potential error gracefully
try:
    numerator = 10
    denominator = 0
    result = numerator / denominator
except ZeroDivisionError:
    print("Error: Cannot divide by zero!")
finally:
    print("Execution completed.")